### PR TITLE
build: fix variable scope issue in undo functionality

### PR DESCRIPTION
**Pull request by chenrui333**
see the following build failure in https://github.com/Homebrew/homebrew-core/pull/170273

```
  main.c:711:5: error: expected expression
                                  move_t old_move;
                                  ^
  main.c:712:25: error: use of undeclared identifier 'old_move'
                                  if (undo_stack_pop(&old_move))
                                                      ^
  main.c:716:9: error: use of undeclared identifier 'old_move'
                                  x = old_move.x;
                                      ^
  main.c:717:9: error: use of undeclared identifier 'old_move'
                                  y = old_move.y;
                                      ^
  main.c:720:31: error: use of undeclared identifier 'old_move'
                                  user_board[posy*9+posx] = old_move.prev_val;
                                                            ^
  5 errors generated.
```

### CODE REVIEW

**Review by jubalh — APPROVED** [review]

**Comment by jubalh** [comment]
Thanks! Which compiler was used when getting this?

**Comment by chenrui333** [comment]
> Thanks! Which compiler was used when getting this?

I am also adding a macos workflow to see if this is reproducible on CI.

**Comment by chenrui333** [comment]
I am using clang

```
CPU: quad-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.39.3 => /usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```
